username_path = """//*[@id="edit-name"]"""
password_path = """//*[@id="edit-pass"]"""
google_username_path = """//*[@id="identifierId"]"""
google_password_path = """//*[@id="password"]/div[1]/div/div[1]/input"""
google_confirm_phone_number_path = """//*[@id="view_container"]/div/div/div[2]/div/div[1]/div/form/span/section/div/div/div/ul/li[3]/div"""
google_phone_number_input_path = """//*[@id="phoneNumberId"]"""
google_text_path = """//*[@id="smsButton"]/div/button/div[2]"""
google_too_many_attempts_path = """//*[@id="view_container"]/div/div/div[2]/div/div[1]/span/section"""
google_verification_input_path = """//*[@id="idvPin"]"""
recovery_phone_messages_path = """//*[@id="msgtbl"]"""
recovery_phone_google_message_path = recovery_phone_messages_path + """/div[2]/div[1]/div[1]/a[contains(text(),"Google")]/parent::*/parent::*/parent::*/div[3]/span/b"""
recovery_phone_refresh_path = """/html/body/div/div[8]/button"""
google_home_path = """//*[@id="yDmH0d"]/c-wiz/div/div[2]/c-wiz/c-wiz/div/div[1]/div[1]/c-wiz/nav/ul/li[1]/a/div[1]"""
spreadsheet_loaded_path = """//*[@id="__HC_94253229"]"""
edit_active_cell_path = """//*[@id="waffle-rich-text-editor" and @aria-label]"""
toggle_shortcuts_path = """//*[starts-with(@class, "apps-ui-material-slide-toggle-container")]"""
go_to_cell_input_path = """//*[@class="jfk-textinput docs-gotoinput-container"]"""
sheets_bold_path = """//*[@aria-label="Bold (Ctrl+B)"]"""
sheets_view_button_path = """//*[@id="docs-view-menu"]"""
sheets_freeze_menu_path = """//*[starts-with(@aria-label, "Freeze") and @class="goog-menuitem-label"]/parent::*/parent::*"""
sheets_format_button_path = """//*[@id="docs-format-menu"]"""
sheets_text_wrapping_menu_path = """//*[starts-with(@aria-label, "Text wrapping") and @class="goog-menuitem-label"]/parent::*/parent::*"""
sheets_text_wrapping_menu_path_2 = """//*[starts-with(@aria-label, "Wrapping") and @class="goog-menuitem-label"]/parent::*/parent::*"""
text_wrapping_clip_path = """//*[starts-with(@class, "goog-menuitem")]/div/span[starts-with(@aria-label, "Clip")]"""
sheets_number_menu_path = """//*[starts-with(@aria-label, "Number") and @class="goog-menuitem-label"]/parent::*/parent::*"""
sheets_autocomplete_menu_path = """//*[starts-with(@aria-label, "Auto-complete") and @class="goog-menuitem-label"]/parent::*/parent::*"""
format_plain_text_path = """//*[starts-with(@class, "goog-menuitem")]/div/span[starts-with(@aria-label, "Plain text")]"""
sheets_tools_button_path = """//*[@id="docs-tools-menu"]"""
sheets_disable_autocomplete_path = """//*[starts-with(@aria-label, "Enable autocomplete") and @class="goog-menuitem-label"]/parent::*/parent::*"""
sheets_filter_views_menu_path = """//*[starts-with(@aria-label, "Filter views") and @class="goog-menuitem-label"]/parent::*/parent::*"""
filter_view_popup_dismiss_path = """//*[@id="waffle-filterbar-promo-dismiss-link"]"""
filter_view_name_path = """//*[@id="waffle-filterbar-name-input"]"""
filter_view_input_path = """//*[@id="waffle-filterbar-range-input"]"""
formula_bar_path = """//*[@id="t-formula-bar-input"]/div"""
sort_column_path = """//*[@class="goog-menu goog-menu-vertical waffle-filterbox-container"]/div[2]"""
filter_view_close_path = """//*[@id="waffle-filter-bar-close"]"""
filterbar_path = """//*[@class="waffle-slidingdialog-filterbar"]"""
filter_views_path = """//*[starts-with(@class, "goog-menu goog-menu-vertical docs-material goog-menu-noaccel waffle-filter-menu")][last()]/div[starts-with(@class, "goog-menuitem apps-menuitem goog-option")]/div"""
sheets_selection_path = """//*[@id="scrollable_right_0"]/div[2]/div[2]"""
sheets_understood_path = """//*[@class="goog-inline-block jfk-button jfk-button-flat waffle-shortcut-override-outside-promo-dismiss-button"]"""
freeze_one_row_path = """//*[starts-with(@class, "goog-menu goog-menu-vertical docs-material goog-menu-noaccel")]/div[2]/div/span[starts-with(@aria-label, "1 row")]"""
freeze_two_columns_path = """//*[starts-with(@class, "goog-menu goog-menu-vertical docs-material goog-menu-noaccel")]/div[8]/div/span[starts-with(@aria-label, "2 columns")]"""
sheets_tab_dropdown_path = """//*[@class="docs-icon goog-inline-block docs-sheet-tab-dropdown"]"""
sheets_tab_rename_path = """//*[starts-with(@class, "goog-menu goog-menu-vertical docs-sheet-tab-menu")]/div[4]"""
sheets_rename_input_path = """//*[@class="docs-sheet-tab-name" and @contenteditable="true"]"""
sheets_text_colour_path = """//*[@class="docs-toolbar-color-menu-button goog-toolbar-menu-button goog-inline-block goog-toolbar-color-menu-button"]"""
sheets_blue_path = """//*[starts-with(@class, "docs-material-colorpalette-cell") and @aria-label="blue"]"""
sheets_red_path = """//*[starts-with(@class, "docs-material-colorpalette-cell") and @aria-label="red"]"""
input_url_path = """//*[starts-with(@id, "bubble-")]/div[1]/div[2]/div/div/div[1]/div[1]/div/div/div[1]/input"""
find_row_path = """//span[starts-with(@aria-label, "Delete row ")]/strong/parent::*"""
find_row_path_2 = """//*[@class="goog-menuitem apps-menuitem"]/div/span[starts-with(@aria-label, "Row ") and not(starts-with(@aria-label, "Row below"))]/strong/span/parent::*/parent::*"""
find_column_path = """//span[starts-with(@aria-label, "Delete column ")]/strong/parent::*"""
find_column_path_2 = """//*[@class="goog-menuitem apps-menuitem"]/div/span[starts-with(@aria-label, "Column ")]/strong/span/parent::*/parent::*"""
add_row_input_path = """//*[@id="0-grid-table-container"]/div[2]/div[2]/div/div[1]/input"""
add_row_button_path = """//*[@id="0-grid-table-container"]/div[2]/div[2]/div/div[1]/div[1]"""
user_menu_path = """//*[@id="block-views-users-user_menu"]/div/div/div/div/p"""
button_path = """//*[@id="block-views-users_charts-user_chart_list"]/div/div/div/div[2]/div[1]/button"""
final_weeks_path = """//*[@id="block-views-charts-charts"]/div/div/div/div[2]/div[last()]/div/div[3]/div[2]/a/div"""
song_link_path = """//h2[@class='song-title no-margin']/a[@href]"""
song_debut_path = """//*[@id="block-views-charts-charts"]/div/div/div/div[2]//span[@class='previous-position position-new']/parent::*/parent::*""" + song_link_path
user_list_path = """//*[@id="block-views-32f0a13b6ed96df9665df3ef2668965a"]/div/div/div/div[@class='view-content']"""
artists_path = """//*[@id="block-views-songs-song_detail"]/div/div/div/div/h2"""
song_name_path = """//*[@id="block-views-songs-song_detail"]/div/div/div/div/h1"""
edit_path = """//*[@id="content"]/div[1]/ul/li[2]/a"""
artist_name_path = """//*[starts-with(@id, "taxonomy-term-")]/div[1]/div/h1"""
song_charts_list_path = """//*[@id="block-system-main"]/div/div/div/div[2]/div/div[2]"""
song_charts_path = song_charts_list_path + """//div[@class="history-item chart-type--weekly-- one-chart-per-week"]"""
